spring:
  main:
    allow-bean-definition-overriding: true

feign:
  circuitbreaker:
    enabled: false  # Disabling this usually stops Feign from spawning new threads

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true